name: Furnish Docker Application

on:
  push:
    branches: [master]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Furnish Docker Dependencies
        run:  npm install

      - name : Install client dependencies
        run:
          cd client
          npm install
          npm test
